### ISSUE TITLE
[DOCS]: Research minimal Docker version for Fonoster

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#688]
Newer versions of the Docker Engine have deprecated the `version` property in Docker Compose. To avoid warnings, we removed the `version` property from all Compose files, including [compose.yaml](https://github.com/fonoster/fonoster/blob/main/compose.yaml) and [compose.dev.yaml](https://github.com/fonoster/fonoster/blob/main/compose.dev.yaml).

As a result, users on older Docker Engine versions have reported errors like:

```
ERROR: The Compose file './compose.yaml' is invalid because:
services.apiserver.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
```

This occurs because older Docker Engine versions don't support the new `expose` format used in these Compose files.

## Task

We need to:

- [ ] **Research and test** the minimum Docker Engine version that can successfully run Fonoster.  
- [ ] **Update the "Prerequisites"** in the [self-hosting documentation](https://github.com/fonoster/fonoster/blob/main/docs/self-hosting/deploy-with-docker.md) to reflect this minimum version requirement.  
- [ ] (Optional) **Note** that while users on older Docker versions might consider adding back the `version` field to their Compose files, we strongly recommend **upgrading** to a newer Docker version for better compatibility and fewer warnings.

**Comment by parz3val** [comment]
I will pick this as I've experience in docker and running in the older docker version.

**Comment by psanders** [comment]
Assigned, @parz3val!

**Comment by Nageswari-droid** [comment]
@psanders I can pick this card!

**Comment by psanders** [comment]
@Nageswari-droid Sounds good. Assigned.

**Comment by psanders** [comment]
This issue hasn't resurfaced since it was created. I'm closing it to tidy things up. If you encounter this issue and end up here, feel free to submit a PR, and I'll gladly review it.
