### ISSUE TITLE
Roadmap for PF 0.1

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#78]
The following items will be the area of focus for `PF 0.1`.

- [x] Allow deploying PF in single-host mode (using docker)
- [x] Enable TLS for the GRPC endpoints and Routr's signaling via Let's Encrypt
- [x] Make using RabbitMQ optional
- [x] Remove MongoDB dependency
- [x] Build from scratch the PVA module to use ARI instead of AGI

**Comment by psanders** [comment]
All done.
